[package]
name = "task"
version = "0.1.0"
edition = "2024"

[dependencies]
x86_64 = "0.15.2"
hal = { path = "../hal" }
util = { path = "../util" }
spin = "0.10.0"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"