[package]
name = "memory"
version = "0.1.0"
edition = "2024"

[dependencies]
linked_list_allocator = "0.10.5"
x86_64 = "0.15.2"
limine = "0.5.0"


[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
