[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = ["-C", "link-arg=-T./kernel/linker.ld", "-C", "link-arg=--nmagic", "-C", "link-arg=-zmax-page-size=0x1000", "-C", "link-arg=-zcommon-page-size=0x1000", "-C", "link-arg=-zseparate-code"]
