name: Build and Release ISO

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
        contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y build-essential xorriso

    - name: Add Kernel target for Rust
      run: rustup target add x86_64-unknown-none

    - name: Build the ISO
      run: make iso

    - name: Create Tag
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag -a "v0.0.${{ github.run_number }}" -m "Auto tag for run ${{ github.run_number }}"
        git push origin "v0.0.${{ github.run_number }}"

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: |
            ./serix.iso
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
