name: Build and Release ISO

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y build-essential xorriso

    - name: Add Kernel target for Rust
      run: rustup target add x86_64-unknown-none

    - name: Build the ISO
      run: make iso

    - name: Create GitHub Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.sha }}
        name: Serix Kernel ISO ${{ github.sha }}
        body: Automated Serix Kernel ISO release for commit ${{ github.sha }}

    - name: Upload ISO to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./serix.iso
        asset_name: serix.iso
        asset_content_type: application/octet-stream
