name: Build and Release ISO

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y build-essential xorriso

    - name: Add Kernel target for Rust
      run: rustup target add x86_64-unknown-none

    - name: Build the ISO
      run: make iso

    - name: Create Tag
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag -a "v0.0.${{ github.run_number }}" -m "Auto tag for run ${{ github.run_number }}"
        git push origin "v0.0.${{ github.run_number }}"

    - name: Create GitHub Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        tag: "v0.0.${{ github.run_number }}"
        name: Serix Kernel ISO "v0.0.${{ github.run_number }}"
        body: Automated Serix Kernel ISO release for commit ${{ github.sha }}
        token: ${{ secrets.PAT }}

    - name: Upload ISO asset via API
      run: |
        curl --fail -X POST \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @./serix.iso \
          "${{steps.create_release.outputs.UPLOAD_URL}}?name=serix.iso"
          
