name: Build and Release ISO on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Rust nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    - name: Install build dependencies
      run: sudo apt update && sudo apt install -y build-essential xorriso

    - name: Add Rust kernel target
      run: rustup target add x86_64-unknown-none

    - name: Build ISO image
      run: make iso

    - name: Create GitHub Release and upload ISO
      uses: softprops/action-gh-release@v2
      with:
        files: serix.iso
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
